title: "M. Nafis Al-Mukhdi"
description: "Website portofolio dan dokumentasi"
baseurl: "" # kosong kalau langsung di domain utama
url: "https://nafis1.my.id"
collections:
  works:
    output: true
    permalink: /works/:title.html
defaults:
  - scope:
      path: ""
      type: pages
    values:
      sitemap: true
  - scope:
      path: ""
      type: works
    values:
      sitemap: true
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

